# Generated by Django 5.2.4 on 2025-07-30 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('father_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.TimeField()),
                ('start_date', models.DateField()),
                ('paid_fee', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('remaining_fee', models.IntegerField()),
                ('reference', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('hold', 'Hold'), ('left', 'Left'), ('pending', 'Pending')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.student')),
            ],
        ),
    ]
