# Generated by Django 5.2.4 on 2025-07-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='placeholder', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='remaining_fee',
            field=models.IntegerField(blank=True),
        ),
    ]
