# Generated by Django 5.2.4 on 2025-08-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_course_name_alter_enrollment_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='paid_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Hold', 'Hold'), ('Left', 'Left'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
