# Generated by Django 5.2.4 on 2025-08-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_student_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
