# Generated by Django 5.2.4 on 2025-08-22 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.TimeField()),
                ('start_date', models.DateField()),
                ('paid_fee', models.IntegerField(default=0)),
                ('discount', models.IntegerField(blank=True, default=0)),
                ('remaining_fee', models.IntegerField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Hold', 'Hold'), ('Left', 'Left'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.student')),
            ],
        ),
    ]
