# Generated by Django 5.2.4 on 2025-08-18 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='hide_completed',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='months_range',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='settings',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.usersetting'),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='filter_duration',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='filter_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='filter_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='filter_order',
            field=models.CharField(default='-id', max_length=20),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='filter_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='filter_statuses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
