# Generated by Django 5.2.4 on 2025-08-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_usersetting_hide_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='filter_duration',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='filter_month',
        ),
    ]
